CREATE TABLE quotes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text          TEXT                                    NOT NULL,
    author        VARCHAR(255)                            NOT NULL,
    source        VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by_id BIGINT,
    CONSTRAINT pk_quotes PRIMARY KEY (id)
);

CREATE TABLE user_quotes
(
    quote_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_quotes PRIMARY KEY (quote_id, user_id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE quotes
    ADD CONSTRAINT FK_QUOTES_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id);

ALTER TABLE user_quotes
    ADD CONSTRAINT fk_usequo_on_quote FOREIGN KEY (quote_id) REFERENCES quotes (id);

ALTER TABLE user_quotes
    ADD CONSTRAINT fk_usequo_on_user FOREIGN KEY (user_id) REFERENCES users (id);